name: CI Setup
runs:
  using: composite
  steps:
    - node: Setup NodeJS 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: node
    - name: Install dependencies
      run: npm ci
      shell: bash