name: Bug Report

title: 'MIB - '
description: Create a bug report

labels:
  - bug

body:
  - type: mardown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
      
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. @einswurmi
    validations:
      required: false

  - type: textarea
    id: what-happend
    attributes:
      label: What happend?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happend, thats uncool..."
    validations:
      required: true

  - type: textarea
    id: already-was-issue
    attributes:
      label: Old issue?
      description: Was this bug already a issue?
    validations:
      required: false
  
  - type: drodown
    id: version
    attributes:
      label: Version
      description: What version of minds are you using?
      options:
        - None (Cause its not released yet...)
    validations:
      required: true
  
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you using?
      options:
        - MacOS
        - Linux
        - Windows 10
        - Windows 11
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      descripton: Please copy and paste any relevant log output. Thus will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDCUT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true