name: CI

on:
  push:
    branches:
      - react
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Tests on ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup/setup-node.yml

      - name: Run tests
        run: npm run test:ci --color

  flow:
    name: Flow

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup/setup-node.yml

      - name: Check types
        run: npm run test:react18:ci

  test_react18:
    name: Test React 18

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup/setup-node.yml

      - name: Run tests with React v18
        run: npm run test:react18:ci

  test_dist:
    name: Test dist

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/ci-setup/setup-node.yml

      - name: Dist tests
        run: npm run test:prod
  
  lint:
    name: Linting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup/setup-node.yml

      - name: ESLint
        run: npm run lint:check

  typescript:
    name: dtsLint

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup/setup-node.yml

      - name: dtsLint
        run: npm run test:typescript